### ISSUE TITLE
Unable to read input sequence

### ISSUE THREAD

**Issue by Castal523** [YaoYinYing/PPRCODE_Guideline#5]
The web version cannot perform sequence analysis and cannot upload sequences in file format. The local running output path command is invalid.Hope can solve it soon,Thank you so much.

**Comment by YaoYinYing** [comment]
Hi @Castal523 can you provide more details like which website is used or how you work with the local command or how's your input file looks like?

If you are not willing to share your sequence here, just feel free and send it to me via emails and I will do some helps.
 
But generally, the input format should be strictly as FASTA. So I would like to recommend you to check it carefully.

**Comment by Castal523** [comment]
Thank you very much for your reply.I checked just now and it is indeed a problem with my input format.Sorry to trouble you！
figure 1 is the website I used(PPRCODE_dev.ipynb - Colaboratory (google.com)).The folder logo&nbsp;seems to be invalid.Thanks again for your reply！！！




All&nbsp;Is&nbsp;Well
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YaoYinYing/PPRCODE_Guideline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月24日(星期五) 晚上10:31
***@***.***&gt;;
抄送:&nbsp;"All Is ***@***.******@***.***&gt;;
主题:&nbsp;Re: [YaoYinYing/PPRCODE_Guideline] Unable to read input sequence (Issue #5)





 
Hi @Castal523 can you provide more details like which website is used or how you work with the local command or how's your input file looks like?
 
If you are not willing to share your sequence here, just feel free and send it to me via emails and I will do some helps.
 
But generally, the input format should be strictly as FASTA. So I would like to recommend you to check it carefully.

**Comment by YaoYinYing** [comment]
Great. If you need to make it easier to process a lot of sequences via uploading, the biolib version is recommended. Check out the readme of this repo for more details.

If there's no more questions, I will close this issue.
